### ISSUE TITLE
Kind-of bug with monitoring crystals

### ISSUE THREAD

**Issue by democat3457** [AranaiRa/ArcaneArchives#103]
Similar to #100, although less buggy. When there are more than one monitoring crystals targeting the same chest (whether its double or not), it *should* only display one "Multiple monitoring crystals" message; however, for each extra monitoring crystal that is placed on the said chest, the "Multiple monitoring crystals" message displays once more, i.e., for three crystals, the message displays 2 times per open - four crystals, 3 times per open - etc.

**Comment by noobanidus** [comment]
I don't understand why it *should* only display one message or why you think this is a bug? Is this just your personal preference, or do you have a specific reason as to why it should only display one? I'm certainly willing to change it if you feel strongly about the matter, but I'm really struggling to understand what your concern is here.

**Comment by democat3457** [comment]
Mainly because when I see "multiple monitoring crystals" I expect to see that all messages targeting the same chest (or block) are "included" under that message. If the message was, say, something along the lines of "Crystal detected on same block", then I'd expect more messages. Also, it does clog up the chat if you happen to have different chests with multiple crystals attached. It's more of a QoL fix than a bug.

**Comment by noobanidus** [comment]
> Also, it does clog up the chat if you happen to have different chests with multiple crystals attached.

*Don't attach multiple monitoring crystals to an inventory*. There is really ***no*** reason to do this. In the past this would actually incorrectly duplicate the contents of the inventory (this only changed recently) and over-represent items in the manifest, which is what lead to this notice being added in the first place.

> Mainly because when I see "multiple monitoring crystals" I expect to see that all messages targeting the same chest (or block) are "included" under that message.

In this instance, "multiple monitoring crystals" is stated because there's the first one that was detected (and the inventory cataloged), and then the position was recorded. Then another one was encountered. Thus, the message says there are multiple monitoring crystals attached, as there are at least 2.

Due to the nature of the code and the fact that each monitoring crystal can be encountered in any order (due to however tiles are loaded from the order of however chunks are loaded), there isn't currently any code implemented to store "A monitoring crystal message has already been reported for this location" and prevent another one from being sent.

> If the message was, say, something along the lines of "Crystal detected on same block", then I'd expect more messages.

That's literally what it's saying. Multiple monitoring crystals have been detected on the same block.

Please, feel free to submit a PR changing the wording of the error message if you find this confusing.

**Comment by democat3457** [comment]
Sounds reasonable. :+1:
