### ISSUE TITLE
Placing Radiant Resonator crashes the game

### ISSUE THREAD

**Issue by democat3457** [AranaiRa/ArcaneArchives#107]
Personally I've been unable to reproduce this, but info here: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/431 https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/413

Seems to me as if the ClientNetwork returned is null; although the ServerNetwork is checked for `null`, the ClientNetwork isn't, not sure why.

**Comment by noobanidus** [comment]
It doesn't check for null because if `getClientNetwork` returns null, it means that the UUID that was passed in was either `null` or the "invalid" value of `00000000-0000-0000-0000-000000000000`. Otherwise it automatically *creates* a new ClientNetwork. It might be confusing and perhaps I should just throw an exception on an invalid UUID instead to make it clearer. 

Regardless, the player's UUID should *never* be `null` or an invalid value. I'm not sure if this is the case now and I didn't spot anything in the linked crash report to support/defend against it, but *generally speaking*, whenever I've run across this problem before (generally this exact crash), it has been the result of someone using a hacked client which, for some reason, does not generate a UUID. I **don't** think running in offline mode (server) would cause this as it generates UUIDs based off the provided username instead.

I'd recommend interfacing with the player in question to ensure this isn't the case.

If it turns out not to be the case, I'd like to know specifically which launcher/server they're using and to get a copy of their playerdata from their server (or their local world) to see more precisely what's going on.

**Comment by Andromander** [comment]
I checked the crash in the linked issue, and they are using a cracked launcher (TLauncher). It's possible to tell because it puts in a "custom cape mod" with the launcher's name in there.

**Comment by noobanidus** [comment]
Ah. Yeah, that would be the issue. In that case, I'm going to close this issue as TLauncher just isn't supported.

**Comment by democat3457** [comment]
That makes sense. Sorry for taking up your time.

**Comment by noobanidus** [comment]
No, that's totally fine! Thanks for reporting it.
