### ISSUE TITLE
Crash with shaders and JEI

### ISSUE THREAD

**Issue by democat3457** [AranaiRa/ArcaneArchives#110]
Crashes when displaying the Radiant Tank with select shaders.

https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/389 (yes it's closed but it's technically still a bug)

**Comment by noobanidus** [comment]
It's a bit odd because that's default Minecraft code. Conversation with Gigaherz suggested changing the rendering method, so:

![](https://i.imgur.com/L3gMOHa.png)

I'll triple-check I can replicate this with 0.2.0.23, and then if it does crash, I'll include this in 0.2.0.24. (As this code doesn't crash with 0.2.0.24 + JEI + Sildur's High).

**Comment by noobanidus** [comment]
So, I can't replicate this with:

- Arcane Archives 0.2.0.19 (version listed in the crash report)
- Optifine 1.12.2-HD-U-F6-pre1
- JEI 1.12.2-4.16.1.302
- Sildur's Vibrant Shaders High

Given that this is just standard Minecraft code (i.e., putting vertex data into the buffer builder) that's crashing because it's trying to add information to the buffer when that index doesn't exist in the buffer... I really don't see what there is I can do to resolve it, especially when I can't replicate it.

**Comment by democat3457** [comment]
Hm ok. (Also there's an Optifine F6?!)

**Comment by noobanidus** [comment]
Can't replicate it with 0.2.0.23 either (latest released version). I presume something else is getting in the way.

**Comment by democat3457** [comment]
also bug here https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/467 that also apparently doesnt use shaders except for internal shaders.

**Comment by democat3457** [comment]
(was this supposed to be "fixed" by 4498e25bea981dbb18d452e2d55b201a79209b2e?)

**Comment by noobanidus** [comment]
I was unable to replicate it with standard optifine or the specified shader set, unfortunately, so I wasn't able to test if 4498e25 fixed it or not. It does bypass `renderModelBrightnessColor` however which hopefully resolves the issue? I'm not sure.

**Comment by noobanidus** [comment]
Although I'll note that the issue you've linked is still using an older version of ArcArc.

**Comment by democat3457** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/496 Apparently this person had the same crash *without shaders* but was still on an old version of the mod.

**Comment by noobanidus** [comment]
I've replied there. I think it is something to do with Optifine and an option that I didn't have configured when I was doing my testing. There is literally no way for me to replicate it, and the error itself is so inexplicable that all I can do is shake my head -- ***it literally should not happen***.
