### ISSUE TITLE
Can't break placed Radiant Trove

### ISSUE THREAD

**Issue by MarcelineMaybe** [AranaiRa/ArcaneArchives#123]
placed it in creative to test the mod and cannot break it now
edit: only breakable in survival

**Comment by AranaiRa** [comment]
Troves can be broken in creative mode only while holding a Scepter of Manipulation. This is mostly a security feature so that you don't accidentally destroy troves full of things if you're doing stuff in creative in an established world. Otherwise yeah, you can hop into Survival to break them as normal.
