### ISSUE TITLE
[Suggestion] Crafttweaker Crafting Table Support

### ISSUE THREAD

**Issue by SureenInk** [AranaiRa/ArcaneArchives#35]
I use a lot of custom crafting recipes in my modpack, and I have several different types of crafting tables that I input recipes into. I was wondering if there was a way to implement crafttweaker support into this mod so that the crafting table can have recipes unique to it (like the gem cutter table has), so that I can lock some recipes behind needing the radiant crafting table.

**Comment by wamc2017** [comment]
I think it's already there... ;)
https://crafttweaker.readthedocs.io/en/latest/#Mods/Arcane_Archives/gct/

**Comment by AranaiRa** [comment]
They're not asking for CT support for the gem cutter's table, they're asking for a way to make a recipe only craftable on the Radiant Crafting Table.

**Comment by SureenInk** [comment]
Yeah, it's not the Gem Cutter's Table. I'm specifically interested in the radiant crafting table.

**Comment by duely** [comment]
Currently the Radiant Crafting table is simply a wrapper around a normal crafting table, it's not a unique system and (from experience) implementing recipes specifically for it while also allowing you to craft IRecipes while also preventing these other recipes from being registered in a normal crafting table... So, basically, it's not going to happen due to difficulty and support issues, and a lack of time to do it.

I'd recommend you check out [Artisan Worktables](https://www.curseforge.com/minecraft/mc-mods/artisan-worktables) by CodeTaylor as an alternative.
